"""Second migration

Revision ID: 5ca267b22137
Revises: fae088abed39
Create Date: 2025-03-31 21:50:21.221915

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5ca267b22137'
down_revision = 'fae088abed39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercisesubmission', sa.Column('execution_logs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercisesubmission', 'execution_logs')
    # ### end Alembic commands ###
