"""First migrations

Revision ID: 840e7b8fd84c
Revises:
Create Date: 2025-03-01 13:47:54.571016

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '840e7b8fd84c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languageimage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('docker_image_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('created', 'building', 'build_succeeded', 'build_failed', 'pushing', 'push_failed', 'pushed', 'pulling', 'pull_failed', 'available', 'testing', 'testing_failed', 'scheduled_for_rebuild', 'scheduled_for_deletion', 'unavailable', 'failed', name='imagestatus'), nullable=False),
    sa.Column('build_logs', sa.JSON(), nullable=True),
    sa.Column('push_logs', sa.JSON(), nullable=True),
    sa.Column('failure_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('test_build', sa.Boolean(), nullable=False),
    sa.Column('file_extension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('build_test_file_content', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
    sa.Column('build_test_std_in', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('build_test_std_out', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requires_compilation', sa.Boolean(), nullable=False),
    sa.Column('compile_file_extension', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('compilation_command', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_execution_command', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entrypoint_script', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
    sa.Column('image_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_architecture', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('languageimage')
    # ### end Alembic commands ###
